### ISSUE TITLE
分享會 NO. 5 (Node.js & Docker)

### ISSUE THREAD

**Issue by litsungyi** [IgsStudySession/StudySession#5]
預計 2016-06-27 @litsungyi 的 Node.js + Docker

**Comment by litsungyiSigono** [comment]
報告在 8f8a5bf17612ac3f4a36995d8d6016bf6619b284

**Comment by litsungyi** [comment]
報告在 8f8a5bf17612ac3f4a36995d8d6016bf6619b284
